  # "gyroscope_noise_density": 0.00028578209809225794,
  # "gyroscope_random_walk": 1.4076485808002456e-05,
  # "accelerometer_noise_density": 0.0012758990589036383,
  # "accelerometer_random_walk": 0.00020040348139970389,

#Accelerometers
accelerometer_noise_density: 0.012758990589036383   #Noise density (continuous-time) X10
accelerometer_random_walk:   0.0020040348139970389   #Bias random walk               X10

#Gyroscopes
gyroscope_noise_density:     0.0028578209809225794   #Noise density (continuous-time)X10
gyroscope_random_walk:       1.4076485808002456e-04   #Bias random walk              X10

rostopic:                    /head_ring/imu      #the IMU ROS topic
update_rate:                 254.0      #Hz (for discretization of the values above)